### ISSUE TITLE
[chart/redis-ha][BUG] AntiAffinity preventing node scheduling due to node capacity

### ISSUE THREAD

**Issue by fabio-510** [DandyDeveloper/charts#6]
**Describe the bug**
Setting hardAntiAffinity to true for *haproxy* makes the pods unschedulable on upgrade when the number of replicas is the same number of kubernetes nodes. The new revision is only scheduled once the pods of the old revision are manually deleted.

**To Reproduce**
1. Create a Kubernetes cluster with 3 nodes
2. Set haproxy hardAntiAffinity value to true
3. Install the chart. At this point no error
4. Upgrade the chart.

**Expected behavior**
The surge happens and the old pods get replaced by the pods of the new revision. But instead pods become unschedulable.

**Comment by DandyDeveloper** [comment]
@fabio-510 This is what is expected for hardAntiAffinity and is more to do with Kubernetes over the chart. As we have a `RollingUpdate` strat, it should replace but the affinity take precedence here.  

One solution would be to lower the replicas on the HAProxy to 2 temporarily, that should fix the problem. 

Do you have a suggestion on how best to work around it? If not, I'll have to come back to this at some point.

**Comment by fabio-510** [comment]
I still don't know how to best do it. I was going through the documentation to see if it's possible to consider the revision as additional criteria for the affinity, but didn't find anything yet.

Will let you know if I find anything

**Comment by fabio-510** [comment]
Ok, I found a solution.
Add the following label to the pod spec and the affinity selector:

revision: "{{ .Release.Revision }}"

**Comment by DandyDeveloper** [comment]
@fabio-510 I see you made a PR then closed it. Everything OK?

**Comment by fabio-510** [comment]
I closed it because I am not sure when I will be able to do all the checks. I will try to open it again today.

**Comment by nunoguerreirorosa** [comment]
Any progress on this issue ? I could use this  fix.
